name: App Checks
on:
  pull_request_target:
    types: [synchronize]
    branches:
      - main

jobs:
  app-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm build
